#gchart_demo:
#    path:  /demo
#    defaults: { _controller: OrcaUserLogBundle:Demo:demo }
#gchart_demo2:
#    path:  /demo2
#    defaults: { _controller: OrcaUserLogBundle:Demo:demo2 }
#gchart_demo3:
#    path:  /demo3
#    defaults: { _controller: OrcaUserLogBundle:Demo:demo3 }
#gchart_demoDeviceType:
#    path:  /demoTypeDevice
#    defaults: { _controller: OrcaUserLogBundle:Demo:demoTypeDevice }

#------------------------------------------------------ demo dashboard ------------------------------------------------- #

dashboard_index:
    path:   /dashboard
    defaults:  { _controller: OrcaUserLogBundle:Dashboard:index }

dashboard_index_:
    path:   /
    defaults:  { _controller: OrcaUserLogBundle:Dashboard:index }

dashboard_connexion:
    path:     /connexions
    defaults: { _controller: OrcaUserLogBundle:Dashboard:connexion }

dashboard_ws_connexion:
    path:     /wsConnexions
    defaults: { _controller: OrcaUserLogBundle:Dashboard:wsConnexion }

dashboard_bo_actions:
    path:     /boActions
    defaults: { _controller: OrcaUserLogBundle:Dashboard:bo }

dashboard_ws_actions:
    path:     /wsActions
    defaults: { _controller: OrcaUserLogBundle:Dashboard:ws }

dashboard_alerte:
    path:     /alertes
    defaults: { _controller: OrcaUserLogBundle:Dashboard:alerte }

dashboard_processlist:
    path:     /processlist
    defaults: { _controller: OrcaUserLogBundle:Dashboard:processlist }

dashboard_ajaxprocesslist:
    path:     /ajaxprocesslist
    defaults: { _controller: OrcaUserLogBundle:Dashboard:Ajaxprocesslist }

dashboard_speedtest:
    path:     /speedtest
    defaults: { _controller: OrcaUserLogBundle:Dashboard:speedtest }

dashboard_ajaxuseractions:
    path:     /timeLine
    defaults: { _controller: OrcaUserLogBundle:Dashboard:timeLine }

dashboard_get_bo_actions_ajax:
  path:     /boActionsAjax
  defaults: { _controller: OrcaUserLogBundle:Dashboard:getBoActionsAjax }

dashboard_get_ws_actions_ajax:
  path:     /wsActionsAjax
  defaults: { _controller: OrcaUserLogBundle:Dashboard:getWSActionsAjax }