#gchart_demo:
#    path:  /demo
#    defaults: { _controller: OrcaUserLogBundle:Demo:demo }
#gchart_demo2:
#    path:  /demo2
#    defaults: { _controller: OrcaUserLogBundle:Demo:demo2 }
#gchart_demo3:
#    path:  /demo3
#    defaults: { _controller: OrcaUserLogBundle:Demo:demo3 }
#gchart_demoDeviceType:
#    path:  /demoTypeDevice
#    defaults: { _controller: OrcaUserLogBundle:Demo:demoTypeDevice }

#------------------------------------------------------ demo dashboard ------------------------------------------------- #

dashboard_index:
    path:   /dashboard
    defaults:  { _controller: OrcaUserLogBundle:Dashboard:index }

dashboard_connexion:
    path:     /connexions
    defaults: { _controller: OrcaUserLogBundle:Dashboard:connexion }

dashboard_erreur:
    path:     /erreurs
    defaults: { _controller: OrcaUserLogBundle:Dashboard:erreur }

dashboard_processlist:
    path:     /processlist
    defaults: { _controller: OrcaUserLogBundle:Dashboard:processlist }

dashboard_ajaxprocesslist:
    path:     /ajaxprocesslist
    defaults: { _controller: OrcaUserLogBundle:Dashboard:Ajaxprocesslist }

dashboard_speedtest:
    path:     /speedtest
    defaults: { _controller: OrcaUserLogBundle:Dashboard:speedtest }