parameters:
    orca_user_log.component.authentication.handler.login_success_handler.class: Orca\UserLogBundle\Component\Authentication\Handler\LoginSuccessHandler
#    orca_user_log.component.authentication.handler.api_login_success_handler.class: Orca\UserLogBundle\Component\Authentication\Handler\ApiLoginSuccessHandler
    orca_user_log.component.authentication.handler.logout_success_handler.class: Orca\UserLogBundle\Component\Authentication\Handler\LogoutSuccessHandler


services:
    orca_user_log.component.authentication.handler.login_success_handler:
        class:  '%orca_user_log.component.authentication.handler.login_success_handler.class%'
        arguments:  ['@doctrine.orm.entity_manager', '@router', '@mobile_detect.mobile_detector','@service_container']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    orca_user_log.component.authentication.handler.logout_success_handler:
        class:  '%orca_user_log.component.authentication.handler.logout_success_handler.class%'
        arguments:  ['@doctrine.orm.entity_manager', '@router', '@mobile_detect.mobile_detector', '@security.token_storage','@service_container' ]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

#    orca_user_log.component.authentication.handler.api_login_success_handler:
#        class: '%orca_user_log.component.authentication.handler.api_login_success_handler.class%'
#        arguments:  ['@lexik_jwt_authentication.jwt_manager', '@event_dispatcher', '@doctrine.orm.entity_manager', '@router', '@mobile_detect.mobile_detector']
#        tags:
#            - { name: 'monolog.logger', channel: 'security' }