<?php

namespace Orca\UserLogBundle\Repository;

/**
 * TblUserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblUserLogRepository extends \Doctrine\ORM\EntityRepository
{
}
